### ISSUE TITLE
Cannot use plugin on Linux

### ISSUE THREAD

**Issue by rocketraman** [rouzwawi/grpc-kotlin#1]
On Linux, I get the following error when running a gradle build with the grpc-kotlin plugin:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':protobufToolsLocator_grpckotlin'.
> Could not find grpc-kotlin-gen-linux-x86_64.exe (io.rouz:grpc-kotlin-gen:0.0.1).
  Searched in the following locations:
      https://nexus.example.com/repository/maven-public/io/rouz/grpc-kotlin-gen/0.0.1/grpc-kotlin-gen-0.0.1-linux-x86_64.exe
```

**Comment by rouzwawi** [comment]
Hi @rocketraman. Sorry for missing your issue. Could you please supply some details about your build setup so I can try to reproduce this.

It looks like it’s looking for a platform specific artifact while the plugin is a java binary, so it should not need to be downloaded with a `linux-x86_64` classifier.

**Comment by rocketraman** [comment]
@rouzwawi Thanks. My build setup is:

Gradle 4.6
Protobuf 3.5.1
gRPC 1.12.0
Kotlin 1.2.50

with the Protobuf gradle plugin 0.8.5.

HTH!

**Comment by 51systems** [comment]
I got this working by rebuilding the artifact and posting it to a maven repository on a nexus server.

The trick was to specify `jdk8` as the classifier so the protobuf gradle plugin could resolve it. The other thing that had to happen was making the jar file executable from linux, which involves adding a preamble to it. 

So in consuming projects, the include became:
```
grpckotlin {
            artifact = "kotlin:grpc-kotlin-gen:0.0.2:jdk8@jar"
        }
```

**Comment by rouzwawi** [comment]
@51systems thanks for the hint! I didn't know about this difference between the Gradle and Maven plugins. The linked PR should resolve this for Gradle on unix-like systems now.

**Comment by rouzwawi** [comment]
Version `0.0.2` is not released and should be usable like

```
grpckotlin {
    artifact = "io.rouz:grpc-kotlin-gen:0.0.2:jdk8@jar"
}
```

**Comment by rocketraman** [comment]
Thank you!
