### ISSUE TITLE
Simplified API for client and server

### ISSUE THREAD

**Issue by wfhartford** [rouzwawi/grpc-kotlin#8]
I'm really glad to see that this project is still getting your attention. When I first found it I saw that no commits had been made in a few months and there was a _early prototype_ disclaimer in the README, so I assumed it was a discarded experiment. Nevertheless, I found it quite useful, and just what I was looking for to use for my new Kotlin based micro services. Over time, I found a couple pain points in both my client and server side code. Every single one of my calls to a client stub looked something like this:
```kotlin
  val response = stub.method(request).await()
```
And every single one of my service method implementations started with something like this:
```kotlin
  fun method(request: Reqeust) = async<Response> {
```
While minor, the need for `async` in every service implementation and `await` on every stub call quickly grew to bother me. One of the design goals of Kotlin's coroutines is that using coroutine code in the standard sequential way can look just like standard blocking code. This idea is described very well in this talk from last year's KotlinConf: [https://www.youtube.com/watch?v=_hfBv0a09Jc]. The async/await part of the talk which starts at about 21 minutes suggests that APIs should default to sequential behaviour without the need for calls to async and await and allow the developer to opt-in to concurrency.

I believe that the code written to implement a service and to use a stub could be simplified by making the functions that the user calls or implements suspending functions which return the simple types.

With this approach, both the service and stub functions end up with the same signature for unary request/response functions:
```kotlin
suspend fun method(request: Request): Response
```
Stub user code is simplified:
```kotlin
val response = stub.method(request)
```
If a stub user does want concurrency, they can opt-in:
```kotlin
val asyncResponse = async { stub.method(request) }
// do other work concurrently
val response = asyncResponse.await()
```
As is service implementation code:
```kotlin
suspend fun method(request: Request): Response {
  return response
}
```
What are your thoughts on a change like this? I'm happy to discuss further or prepare a pull request.

**Comment by rouzwawi** [comment]
@wfhartford I think you have an excellent point and it's clear that this is the way to go when looking at the talk from KotlinConf. I was actually experimenting with this approach while working on the other PR, but was a bit ambivalent on which way to go. But if it's idiomatic Kotlin style, I'll all for it!

On a similar note, what's your thoughts on the streaming (either way) rpcs? Specially for the client streaming rcps where the return value(s) aren't available until after some sends from the client.

**Comment by rouzwawi** [comment]
Unary fix: https://github.com/rouzwawi/grpc-kotlin/pull/7/commits/6335eec80f816dad0debd17e8a06e3785c010b90

**Comment by rouzwawi** [comment]
One option for client streaming calls is to just mimic the server signature like

```kotlin
// server
suspend fun greetClientStream(requestChannel: ReceiveChannel<GreetRequest>): GreetReply

// client
val reply = stub.greetClientStream {
    // ProducerScope in here
    send(/*request*/)
    send(/*request*/)
}
```

**Comment by wfhartford** [comment]
It's nice to see that we're on the same page with that.

For streaming request / unary response, the sample from your comment looks really nice.

I have a hard time making recommendations about the streaming features since I have not really used them other than experimentation.

The server functions for the server streaming scenario could be made extension functions on the `ProducerScope<T>` interface? That would allow the following:
```kotlin
// server
    override suspend fun ProducerScope<GreetReply>.greetServerStream(request: GreetRequest) {
        send(...)
        send(...)
    }
```
I don't see any problem with the way client code calls these server streaming functions.

For bidirectional streaming, it should be possible to combine the two approaches.
